In [13]:
import numpy as np 


n = 3
h = 0.25
A = np.array([[-2, 1, 0],
              [1, -2, 1],
              [0, 1, -2]])
U = np.zeros((n, n), dtype=float)

U[0] = A[0]

L = np.eye(n, dtype=float)

for k in range(0, n-1):
    for i in range(k+1, n):
        l = A[i][k] / U[k][k]
        L[i][k] = l

        for j in range(k, n):
            U[i][j] = A[i][j] - l * U[k][j]

print("U matrix")
print(U)
print("L matrix")
print(L)

print("A matrix (=LU)")
print(A)
print("LU")
print(np.matmul(L, U))


U matrix
[[-2.          1.          0.        ]
 [ 0.         -1.5         1.        ]
 [ 0.          0.         -1.33333333]]
L matrix
[[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [-0.         -0.66666667  1.        ]]
A matrix (=LU)
[[-2  1  0]
 [ 1 -2  1]
 [ 0  1 -2]]
LU
[[-2.  1.  0.]
 [ 1. -2.  1.]
 [ 0.  1. -2.]]
